import { Darker_Grotesque, Geist } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";

const darkerSans = Darker_Grotesque({
	variable: "--font-darker-sans",
	subsets: ["latin"],
});
const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

export const metadata = {
	title: "Ember",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html
			lang="en"
			className={`${darkerSans.variable} ${geistSans.variable}`}
		>
			<body>{children}</body>
		</html>
	);
}
